//
//  SurahData.swift
//  Quran
//
//  Created by Joseph Hayes on 12/07/2024.
//

import Foundation

struct Surah: Identifiable {
    let id = UUID()
    let name: String
    let audioFileName: String
    let imageFileName: String
}

let surahs: [Surah] = [
    Surah(name: "Al-Fatiha", audioFileName: "001", imageFileName: "image1"),
    Surah(name: "Al-Baqarah", audioFileName: "002", imageFileName: "image2"),
    Surah(name: "Aal-E-Imran", audioFileName: "003", imageFileName: "image3"),
    Surah(name: "An-Nisa'", audioFileName: "004", imageFileName: "image4"),
    Surah(name: "Al-Ma'idah", audioFileName: "005", imageFileName: "image5"),
    Surah(name: "Al-An'am", audioFileName: "006", imageFileName: "image6"),
    Surah(name: "Al-A'raf", audioFileName: "007", imageFileName: "image7"),
    Surah(name: "Al-Anfal", audioFileName: "008", imageFileName: "image8"),
    Surah(name: "At-Tawbah", audioFileName: "009", imageFileName: "image9"),
    Surah(name: "Yunus", audioFileName: "010", imageFileName: "image10"),
    Surah(name: "Hud", audioFileName: "011", imageFileName: "image11"),
    Surah(name: "Yusuf", audioFileName: "012", imageFileName: "image12"),
    Surah(name: "Ar-Ra'd", audioFileName: "013", imageFileName: "image13"),
    Surah(name: "Ibrahim", audioFileName: "014", imageFileName: "image14"),
    Surah(name: "Al-Hijr", audioFileName: "015", imageFileName: "image15"),
    Surah(name: "An-Nahl", audioFileName: "016", imageFileName: "image16"),
    Surah(name: "Al-Isra", audioFileName: "017", imageFileName: "image17"),
    Surah(name: "Al-Kahf", audioFileName: "018", imageFileName: "image18"),
    Surah(name: "Maryam", audioFileName: "019", imageFileName: "image19"),
    Surah(name: "Ta-Ha", audioFileName: "020", imageFileName: "image20"),
    Surah(name: "Al-Anbiya'", audioFileName: "021", imageFileName: "image21"),
    Surah(name: "Al-Hajj", audioFileName: "022", imageFileName: "image22"),
    Surah(name: "Al-Mu'minun", audioFileName: "023", imageFileName: "image23"),
    Surah(name: "An-Nur", audioFileName: "024", imageFileName: "image24"),
    Surah(name: "Al-Furqan", audioFileName: "025", imageFileName: "image25"),
    Surah(name: "Ash-Shu'ara", audioFileName: "026", imageFileName: "image26"),
    Surah(name: "An-Naml", audioFileName: "027", imageFileName: "image27"),
    Surah(name: "Al-Qasas", audioFileName: "028", imageFileName: "image28"),
    Surah(name: "Al-Ankabut", audioFileName: "029", imageFileName: "image29"),
    Surah(name: "Ar-Rum", audioFileName: "030", imageFileName: "image30"),
    Surah(name: "Luqman", audioFileName: "031", imageFileName: "image31"),
    Surah(name: "As-Sajda", audioFileName: "032", imageFileName: "image32"),
    Surah(name: "Al-Ahzab", audioFileName: "033", imageFileName: "image33"),
    Surah(name: "Saba'", audioFileName: "034", imageFileName: "image34"),
    Surah(name: "Fatir", audioFileName: "035", imageFileName: "image35"),
    Surah(name: "Ya-Sin", audioFileName: "036", imageFileName: "image36"),
    Surah(name: "As-Saffat", audioFileName: "037", imageFileName: "image37"),
    Surah(name: "Sad", audioFileName: "038", imageFileName: "image38"),
    Surah(name: "Az-Zumar", audioFileName: "039", imageFileName: "image39"),
    Surah(name: "Ghafir", audioFileName: "040", imageFileName: "image40"),
    Surah(name: "Fussilat", audioFileName: "041", imageFileName: "image41"),
    Surah(name: "Ash-Shura", audioFileName: "042", imageFileName: "image42"),
    Surah(name: "Az-Zukhruf", audioFileName: "043", imageFileName: "image43"),
    Surah(name: "Ad-Dukhan", audioFileName: "044", imageFileName: "image44"),
    Surah(name: "Al-Jathiya", audioFileName: "045", imageFileName: "image45"),
    Surah(name: "Al-Ahqaf", audioFileName: "046", imageFileName: "image46"),
    Surah(name: "Muhammad", audioFileName: "047", imageFileName: "image47"),
    Surah(name: "Al-Fath", audioFileName: "048", imageFileName: "image48"),
    Surah(name: "Al-Hujurat", audioFileName: "049", imageFileName: "image49"),
    Surah(name: "Qaf", audioFileName: "050", imageFileName: "image50"),
    Surah(name: "Adh-Dhariyat", audioFileName: "051", imageFileName: "image51"),
    Surah(name: "At-Tur", audioFileName: "052", imageFileName: "image52"),
    Surah(name: "An-Najm", audioFileName: "053", imageFileName: "image53"),
    Surah(name: "Al-Qamar", audioFileName: "054", imageFileName: "image54"),
    Surah(name: "Ar-Rahman", audioFileName: "055", imageFileName: "image55"),
    Surah(name: "Al-Waqi'a", audioFileName: "056", imageFileName: "image56"),
    Surah(name: "Al-Hadid", audioFileName: "057", imageFileName: "image57"),
    Surah(name: "Al-Mujadila", audioFileName: "058", imageFileName: "image58"),
    Surah(name: "Al-Hashr", audioFileName: "059", imageFileName: "image59"),
    Surah(name: "Al-Mumtahina", audioFileName: "060", imageFileName: "image60"),
    Surah(name: "As-Saff", audioFileName: "061", imageFileName: "image61"),
    Surah(name: "Al-Jumu'a", audioFileName: "062", imageFileName: "image62"),
    Surah(name: "Al-Munafiqun", audioFileName: "063", imageFileName: "image63"),
    Surah(name: "At-Taghabun", audioFileName: "064", imageFileName: "image64"),
    Surah(name: "At-Talaq", audioFileName: "065", imageFileName: "image65"),
    Surah(name: "At-Tahrim", audioFileName: "066", imageFileName: "image66"),
    Surah(name: "Al-Mulk", audioFileName: "067", imageFileName: "image67"),
    Surah(name: "Al-Qalam", audioFileName: "068", imageFileName: "image68"),
    Surah(name: "Al-Haqqah", audioFileName: "069", imageFileName: "image69"),
    Surah(name: "Al-Ma'arij", audioFileName: "070", imageFileName: "image70"),
    Surah(name: "Nuh", audioFileName: "071", imageFileName: "image71"),
    Surah(name: "Al-Jinn", audioFileName: "072", imageFileName: "image72"),
    Surah(name: "Al-Muzzammil", audioFileName: "073", imageFileName: "image73"),
    Surah(name: "Al-Muddathir", audioFileName: "074", imageFileName: "image74"),
    Surah(name: "Al-Qiyama", audioFileName: "075", imageFileName: "image75"),
    Surah(name: "Al-Insan", audioFileName: "076", imageFileName: "image76"),
    Surah(name: "Al-Mursalat", audioFileName: "077", imageFileName: "image77"),
    Surah(name: "An-Naba'", audioFileName: "078", imageFileName: "image78"),
    Surah(name: "An-Nazi'at", audioFileName: "079", imageFileName: "image79"),
    Surah(name: "Abasa", audioFileName: "080", imageFileName: "image80"),
    Surah(name: "At-Takwir", audioFileName: "081", imageFileName: "image81"),
    Surah(name: "Al-Infitar", audioFileName: "082", imageFileName: "image82"),
    Surah(name: "Al-Mutaffifin", audioFileName: "083", imageFileName: "image83"),
    Surah(name: "Al-Inshiqaq", audioFileName: "084", imageFileName: "image84"),
    Surah(name: "Al-Buruj", audioFileName: "085", imageFileName: "image85"),
    Surah(name: "At-Tariq", audioFileName: "086", imageFileName: "image86"),
    Surah(name: "Al-A'la", audioFileName: "087", imageFileName: "image87"),
    Surah(name: "Al-Ghashiyah", audioFileName: "088", imageFileName: "image88"),
    Surah(name: "Al-Fajr", audioFileName: "089", imageFileName: "image89"),
    Surah(name: "Al-Balad", audioFileName: "090", imageFileName: "image90"),
    Surah(name: "Ash-Shams", audioFileName: "091", imageFileName: "image91"),
    Surah(name: "Al-Lail", audioFileName: "092", imageFileName: "image92"),
    Surah(name: "Ad-Duhaa", audioFileName: "093", imageFileName: "image93"),
    Surah(name: "Ash-Sharh", audioFileName: "094", imageFileName: "image94"),
    Surah(name: "At-Tin", audioFileName: "095", imageFileName: "image95"),
    Surah(name: "Al-Alaq", audioFileName: "096", imageFileName: "image96"),
    Surah(name: "Al-Qadr", audioFileName: "097", imageFileName: "image97"),
    Surah(name: "Al-Bayyina", audioFileName: "098", imageFileName: "image98"),
    Surah(name: "Az-Zalzala", audioFileName: "099", imageFileName: "image99"),
    Surah(name: "Al-Adiyat", audioFileName: "100", imageFileName: "image100"),
    Surah(name: "Al-Qaria", audioFileName: "101", imageFileName: "image101"),
    Surah(name: "At-Takathur", audioFileName: "102", imageFileName: "image102"),
    Surah(name: "Al-Asr", audioFileName: "103", imageFileName: "image103"),
    Surah(name: "Al-Humaza", audioFileName: "104", imageFileName: "image104"),
    Surah(name: "Al-Fil", audioFileName: "105", imageFileName: "image105"),
    Surah(name: "Quraish", audioFileName: "106", imageFileName: "image106"),
    Surah(name: "Al-Ma'un", audioFileName: "107", imageFileName: "image107"),
    Surah(name: "Al-Kawthar", audioFileName: "108", imageFileName: "image108"),
    Surah(name: "Al-Kafiroon", audioFileName: "109", imageFileName: "image109"),
    Surah(name: "An-Nasr", audioFileName: "110", imageFileName: "image110"),
    Surah(name: "Al-Masad", audioFileName: "111", imageFileName: "image111"),
    Surah(name: "Al-Ikhlas", audioFileName: "112", imageFileName: "image112"),
    Surah(name: "Al-Falaq", audioFileName: "113", imageFileName: "image113"),
    Surah(name: "An-Nas", audioFileName: "114", imageFileName: "image114")
]




